// Warning: this file is automatically generated by `npm run update-prefixes`
export default {
  "prefixes": [
    "fasdt",
    "fasds",
    "fasdr",
    "fasdl",
    "fast",
    "fass",
    "fasr",
    "fasl",
    "fadt",
    "fad",
    "fadr",
    "fadl",
    "fat",
    "fas",
    "far",
    "fal",
    "fab"
  ],
  "styles": [
    "thin",
    "solid",
    "regular",
    "light",
    "brands"
  ],
  "families": [
    "sharp-duotone",
    "sharp",
    "duotone",
    "classic"
  ],
  "familyStyleToPrefixMap": {
    "sharp-duotone": {
      "thin": "fasdt",
      "solid": "fasds",
      "regular": "fasdr",
      "light": "fasdl"
    },
    "sharp": {
      "thin": "fast",
      "solid": "fass",
      "regular": "fasr",
      "light": "fasl"
    },
    "duotone": {
      "thin": "fadt",
      "solid": "fad",
      "regular": "fadr",
      "light": "fadl"
    },
    "classic": {
      "thin": "fat",
      "solid": "fas",
      "regular": "far",
      "light": "fal",
      "brands": "fab"
    }
  },
  "prefixToFamilyStyleMap": {
    "fasdt": {
      "family": "sharp-duotone",
      "style": "thin"
    },
    "fasds": {
      "family": "sharp-duotone",
      "style": "solid"
    },
    "fasdr": {
      "family": "sharp-duotone",
      "style": "regular"
    },
    "fasdl": {
      "family": "sharp-duotone",
      "style": "light"
    },
    "fast": {
      "family": "sharp",
      "style": "thin"
    },
    "fass": {
      "family": "sharp",
      "style": "solid"
    },
    "fasr": {
      "family": "sharp",
      "style": "regular"
    },
    "fasl": {
      "family": "sharp",
      "style": "light"
    },
    "fadt": {
      "family": "duotone",
      "style": "thin"
    },
    "fad": {
      "family": "duotone",
      "style": "solid"
    },
    "fadr": {
      "family": "duotone",
      "style": "regular"
    },
    "fadl": {
      "family": "duotone",
      "style": "light"
    },
    "fat": {
      "family": "classic",
      "style": "thin"
    },
    "fas": {
      "family": "classic",
      "style": "solid"
    },
    "far": {
      "family": "classic",
      "style": "regular"
    },
    "fal": {
      "family": "classic",
      "style": "light"
    },
    "fab": {
      "family": "classic",
      "style": "brands"
    }
  }
}